apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: linkscope
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true

  dashboard-provider.yml: |
    apiVersion: 1
    providers:
      - name: "default"
        folder: ""
        type: file
        options:
          path: /var/lib/grafana/dashboards