apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: linkscope
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: "linkscope-api"
        static_configs:
          - targets: ["app-service:8000"]
        metrics_path: /metrics
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
