apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: linkscope
spec:
  selector:
    app: linkscope-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
